### ISSUE TITLE
Using 1L/2LOS channel ntuples

### ISSUE THREAD

**Issue by SimonBerlendis** [maxwellcui/4top#14]
Hey Maxwell, 
How is it going on with the new ntuples ? Did you manage to use them in your TMVA code ? 
Cheers, Simon.

**Comment by maxwellcui** [comment]
Hi, I was off town most of time last week and just got back on Sunday evening, so no update yet.
I'm getting my hands on now. Should have some results by Thursday.

**Comment by SimonBerlendis** [comment]
Ok. If you have any questions concerning the ntuples, put them here and I will try to answer them.

**Comment by maxwellcui** [comment]
Can you give me the path to the ntuples on lxplus again? Thanks.

**Comment by SimonBerlendis** [comment]
/eos/atlas/atlascerngroupdisk/phys-top/4tops/ljetsOS/cutflow/v2/

2018-06-19 13:29 GMT-07:00 Maxwell Cui <notifications@github.com>:

**Comment by SimonBerlendis** [comment]
Hey,

This is the signal regions definitions that were used in the previous analysis (they might change in the new iteration):

```
SRs = [ 
        'met_met>20000 and mtw + met_met>60000 and nbjet==3 and njet==9 and nJ==0 and (ejets or mujets)',\
        'met_met>20000 and mtw + met_met>60000 and nbjet==3 and njet==9 and nJ==1 and (ejets or mujets)',\
        'met_met>20000 and mtw + met_met>60000 and nbjet==3 and njet==9 and nJ>1 and (ejets or mujets)',\
        'met_met>20000 and mtw + met_met>60000 and nbjet>3 and njet==9 and nJ==0 and (ejets or mujets)',\
        'met_met>20000 and mtw + met_met>60000 and nbjet>3 and njet==9 and nJ==1 and (ejets or mujets)',\
        'met_met>20000 and mtw + met_met>60000 and nbjet>3 and njet==9 and nJ>1 and (ejets or mujets)',\
        'met_met>20000 and mtw + met_met>60000 and nbjet==3 and njet>9 and nJ==0 and (ejets or mujets)',\
        'met_met>20000 and mtw + met_met>60000 and nbjet==3 and njet>9 and nJ==1 and (ejets or mujets)',\
        'met_met>20000 and mtw + met_met>60000 and nbjet==3 and njet>9 and nJ>1 and (ejets or mujets)',\
        'met_met>20000 and mtw + met_met>60000 and nbjet>3 and njet>9 and nJ==0 and (ejets or mujets)',\
        'met_met>20000 and mtw + met_met>60000 and nbjet>3 and njet>9 and nJ==1 and (ejets or mujets)',\
        'met_met>20000 and mtw + met_met>60000 and nbjet>3 and njet>9 and nJ>1 and (ejets or mujets)',\
        'nbjet==3 and njet==7 and nJ==0 and (  (  ( OSee or OSmumu ) and  abs(mll-91)>8 and mll>50 )  or OSemu )',\
        'nbjet==3 and njet==7 and nJ>0 and (  (  ( OSee or OSmumu ) and  abs(mll-91)>8 and mll>50 )  or OSemu )',\
        'nbjet>3 and njet==7 and nJ==0 and (  (  ( OSee or OSmumu ) and  abs(mll-91)>8 and mll>50 )  or OSemu )',\
        'nbjet>3 and njet==7 and nJ>0 and (  (  ( OSee or OSmumu ) and  abs(mll-91)>8 and mll>50 )  or OSemu )',\
        'nbjet==3 and njet>7 and nJ==0 and (  (  ( OSee or OSmumu ) and  abs(mll-91)>8 and mll>50 )  or OSemu )',\
        'nbjet==3 and njet>7 and nJ>0 and (  (  ( OSee or OSmumu ) and  abs(mll-91)>8 and mll>50 )  or OSemu )',\
        'nbjet>3 and njet>7 and nJ==0 and (  (  ( OSee or OSmumu ) and  abs(mll-91)>8 and mll>50 )  or OSemu )',\
        'nbjet>3 and njet>7 and nJ>0 and (  (  ( OSee or OSmumu ) and  abs(mll-91)>8 and mll>50 )  or OSemu )'\
```

The formula for MTW is the following:
```

float toolTTHbb::MTW(int channel){

  if(channel == 1){
    for(unsigned int i_el=0; i_el<m_ntuple->el_pt->size(); i_el++){
      if( (bool)m_ntuple->el_isTight->at(i_el) ){
        return std::sqrt( 2*m_ntuple->el_pt->at(i_el)*m_ntuple->met_met*
                          (1-std::cos(m_ntuple->el_phi->at(i_el)-m_ntuple->met_phi)) );
      }
    }
  }

  else if(channel == 2){
    for(unsigned int i_mu=0; i_mu<m_ntuple->mu_pt->size(); i_mu++){
      if( (bool)m_ntuple->mu_isTight->at(i_mu) ){
        return std::sqrt( 2*m_ntuple->mu_pt->at(i_mu)*m_ntuple->met_met*
                          (1-std::cos(m_ntuple->mu_phi->at(i_mu)-m_ntuple->met_phi)) );
      }
    }
  }

  return 0;
}
```

**Comment by maxwellcui** [comment]
Thanks

**Comment by maxwellcui** [comment]
Hi @SimonBerlendis, I am listing the flags for the preselection here. Can you check if I am correct with these? Just in case I made mistakes or missed something. Thanks!

## Single lepton
`ejets_2017_MV2c10 `
`mujets_2017_MV2c10 `

## Dilepton
`ee_2017_MV2c10` 
`mumu_2017_MV2c10`
`emu_2017_MV2c10`

## B-tagging@77% efficiency (number of b jet)
` nBTags_77`

## Missing transverse energy
`met_met`

## Number of jets
`nJets`

**Comment by SimonBerlendis** [comment]
That sounds correct to me. 
You can also get the number of jets by looking at the size of jet_pt (jet_pt->size()), and the number of b-jets by looking at the number of jets that pass the jet_isbtagged_MV2c10_77 flag:
```
  int NBjet =0;
  for(unsigned int i_jet=0; i_jet<m_ntuple->jet_pt->size(); i_jet++)
    if( (bool)m_ntuple->jet_isbtagged_MV2c10_77->at(i_jet) )
      NBjet++;
```
You can also get the jet activities by summing the jet pt in the event:
```
  Double_t ht =0;
  for(unsigned int i_jet=0; i_jet<m_ntuple->jet_pt->size(); i_jet++)
      ht += m_ntuple->jet_pt->at(i_jet);
```

**Comment by maxwellcui** [comment]
Any preference which method should I use to find the number of jet and b jet?

**Comment by SimonBerlendis** [comment]
No preference. Just use what is simple for you.

**Comment by SimonBerlendis** [comment]
How it is going on your side ? 
Did you manage to get some results with these ntuples ? 
Simon.

**Comment by maxwellcui** [comment]
The code is done and on the lxplus now, but has some run time error. I'm still debugging.
It's the end of summer 1 session. I'm kinda busy with the TA job, so I don't distribute too much time on the research but will put a lot more time on this starting from summer 2, about 1 week later.

**Comment by SimonBerlendis** [comment]
Hi Max. Yes, you can download the files using the rucio command, but it only works in a machine where the ATLAS environment is installed, which I don't think it's the case of your local machine. But it is, then you can download it by doing `rucio download <datatsetname>`. But you need to get a valid grid certificate to do that and I don't remember if you did the procedure to get one (https://twiki.cern.ch/twiki/bin/view/AtlasComputing/SoftwareTutorialSoftwareBasics#Grid_Certificates). Simon.

**Comment by SimonBerlendis** [comment]
The weight formula:
```
Double_t toolTTHbb::GetWeight(Double_t lumi)
{
  return lumi * 1000 * XSectTimesKFact / m_ntuple->m_totalEventsWeighted
    * m_ntuple->weight_mc * m_ntuple->weight_pileup * m_ntuple->weight_leptonSF
    * m_ntuple->weight_bTagSF_MV2c10_77 * m_ntuple->weight_jvt ;
}
```

**Comment by SimonBerlendis** [comment]
And for the cross section times k-factor:
```
 DSID    xsec       k-fac
410080   0.0091622   1.0042
410470   396.842   1.1398
410501   397.088   1.13913198296
```
