### ISSUE TITLE
Jul.6 meeting note

### ISSUE THREAD

**Issue by maxwellcui** [maxwellcui/4top#15]
## Preselection
Channel: 1L/2LOS
Signal region listed in #14 
Signal file: `410080`
Background file: `410501`

Criteria applied:
`met_met>20GeV` 
`nbjet=3 and njet=9` for single lepton
`nbjet==3 and njet==7` for dilepton

## Training 
Training variables
`met_met`
`el_pt[0]`
`el_eta[0]`
`jet_pt[0]`
`jet_eta[0]`
`njet`
`nbjet`

![variables_id_c1](https://user-images.githubusercontent.com/18160028/42376997-366fca3a-80d6-11e8-9bd6-6a91c1515353.png)
![variables_id_c2](https://user-images.githubusercontent.com/18160028/42376998-3689d5e2-80d6-11e8-8dd7-221571ed1c9a.png)
![correlationmatrixb](https://user-images.githubusercontent.com/18160028/42377044-70967f38-80d6-11e8-9d56-29e0de64e46b.png)
![correlationmatrixs](https://user-images.githubusercontent.com/18160028/42377045-70ab71b8-80d6-11e8-965d-30fe49f4e871.png)
![rejbvss](https://user-images.githubusercontent.com/18160028/42377060-829e143e-80d6-11e8-9e41-706bb9e73fe5.png)
### Ranking input variables (method unspecific)...
```
IdTransformation         : Ranking result (top variable is best ranked)
                         : -----------------------------------
                         : Rank : Variable   : Separation
                         : -----------------------------------
                         :    1 : nJets      : 8.273e-02
                         :    2 : jet_pt[0]  : 6.668e-02
                         :    3 : nBTags_77  : 6.569e-02
                         :    4 : jet_eta[0] : 4.955e-02
                         :    5 : met_met    : 4.127e-02
                         :    6 : el_eta[0]  : 3.351e-02
                         :    7 : el_pt[0]   : 3.140e-02
                         : -----------------------------------
```
 ###   Ranking input variables (method specific)...
```
T850_D3_S2.500000        : Ranking result (top variable is best ranked)
                         : --------------------------------------------
                         : Rank : Variable   : Variable Importance
                         : --------------------------------------------
                         :    1 : jet_eta[0] : 1.891e-01
                         :    2 : el_eta[0]  : 1.817e-01
                         :    3 : met_met    : 1.435e-01
                         :    4 : el_pt[0]   : 1.396e-01
                         :    5 : jet_pt[0]  : 1.387e-01
                         :    6 : nJets      : 1.272e-01
                         :    7 : nBTags_77  : 8.008e-02
```
```
                         : Evaluation results ranked by best signal efficiency and purity (area)
                         : -------------------------------------------------------------------------------------------------------------------
                         : DataSet       MVA                       
                         : Name:         Method:          ROC-integ
                         : dataset       T850_D3_S2.500000: 0.746
                         : -------------------------------------------------------------------------------------------------------------------
                         : 
                         : Testing efficiency compared to training efficiency (overtraining check)
                         : -------------------------------------------------------------------------------------------------------------------
                         : DataSet              MVA              Signal efficiency: from test sample (from training sample) 
                         : Name:                Method:          @B=0.01             @B=0.10            @B=0.30   
                         : -------------------------------------------------------------------------------------------------------------------
                         : dataset              T850_D3_S2.500000: 0.108 (0.203)       0.377 (0.514)      0.667 (0.752)
                         : -------------------------------------------------------------------------------------------------------------------
```

## Next step
1. Try out different signal region
2. Adding MTW in preselection
3. Adding file weight
4. BDT options study
![rejbvss](https://user-images.githubusercontent.com/18160028/42377595-bb943640-80d8-11e8-9b57-b55a1c605ec1.png)

**Comment by SimonBerlendis** [comment]
Hi Max,

Few questions/remarks:
 * What does "T850_D3_S2.500000" mean/stand for ? 
 * Can you add HT (Sum of jet Pts) in the list of input variables ? 
 * If the events contains only muons, then using el_pt/el_eta  doesn't make sense here. You should use mu_pt/eta instead.
 * Can you also add the Pt/Eta of the 2nd jet? Also for the 2nd lepton if you have a 2LOS event ? 
 * Can you also plot the significance (=s/sqrt(s+b), where s is the signal yield, and b the background yield) for a luminosity of 150fb-1 in function of the different cut on the BDT output ?  
 * It would interesting to check the results for different pre-selection criteria (by loosing the jet/b-jets multiplicity requirement for example). 

Cheers, Simon.

**Comment by maxwellcui** [comment]
T is number of trees, D is maximum depth, S is node size
The result above is just a tryout result. I'm gonna work on this now.
Input variables are easy to fix except int the case of second lepton, I will need find out a way to do that. Probably need to extract it in the data preparation.

**Comment by SimonBerlendis** [comment]
I just want to share you these good lectures from Glen Cowan (the god of statistics in particle physics). 
https://indico.cern.ch/event/77830/
https://indico.cern.ch/event/77831/
https://indico.cern.ch/event/77832/
https://indico.cern.ch/event/77833/ 
They would hopefully give you a little more insight on the statistical method that we use in ATLAS.

**Comment by maxwellcui** [comment]
Believe or not, July 2016, I attended the iSTEP summer school in Tsinghua University. He was teaching the statistics. And I fell asleep....
The only thing I remember is he speaks decent Chinese....

**Comment by SimonBerlendis** [comment]
Well, that's unfortunate. These lectures are the references of statistics in particle physics :)
