### ISSUE TITLE
Calculation of weight of the file

### ISSUE THREAD

**Issue by maxwellcui** [maxwellcui/4top#2]
The file weight is not calculated in the data preparation stage. 
Need to add up all of the event weights.

**Comment by maxwellcui** [comment]
File weight varies dramatically among files, ranging from 0.01 to 1000.

**Comment by maxwellcui** [comment]
Better to show the file weight with the process

**Comment by maxwellcui** [comment]
Background

|DSID|Process|Weight|
|---|---|---|
||***ttbar+V***|
|410155|ttbar+W|249.117|
|410218|ttbar+Z|119.2|
|410219|ttbar+Z|147.503|
|410220|ttbar+Z|14.724|
||***Other top***|
|410080|4 top|9.13915|
|410050|tZ|67.4766|
|410081|ttbar+WW|9.62296|
||***Diboson***|
|361063|ZZ->llll|66.6092|
|361064|ZW->lllv SF Minus|51.1022|
|361065|ZW->lllv OF Minus|59.0429|
|361066|ZW->lllv SF Plus|65.1792|
|361067|ZW->lllv OF Plus|72.8302|
|361070 |WW|12.6834|
|361071|ZW|8.89371|
|361072|ZZ|1.64396|
|361073|gg->llll|2.27258|
||***Triboson***|
|361620|WWW->lvlvlv|1.65053|
|361621|WWZ->lvlvll|0.883388|
|361622|WWZ->lvlvvv|0.0192489|
|361624|WZZ->lvllvv|0.199645|
|361625|ZZZ->llllll|0.015261|
|361626|ZZZ->llllvv|0.0250936|
||***VH***|
|342284|WH,W->Any, H->incl|5.02937|
|342285|ZH,Z->Any, H->incl|2.0966|
||***ttbarH***|
|343365|ttbarH dilep|27.99|
|343366|ttbarH semilep|55.2383|
|343367|ttbarH allhadr|0.27182|

**Comment by SimonBerlendis** [comment]
Indeed, these weights are proportional to the cross section of each process (and the filter efficiency). What is the name of this variable in the TTree ?

**Comment by maxwellcui** [comment]
This variable is not included in the original simulation file. I calculate and store it in a new TTree on my local machine for the training, but the algorithm can be found in (https://github.com/maxwellcui/4top/blob/master/dataPreparation/prepTree.C#L191)
